using System.Text.RegularExpressions;

namespace Mediocr.Test;

using FluentAssertions;
using Xunit;

/// <summary>
/// Snapshot tests that verify the exact generated output
/// </summary>
public class GeneratedCodeSnapshotTests
{
    private readonly RequestHandlerGenerator _generator = new();
    
    [Fact]
    public void GeneratedCode_MatchesExpectedSnapshot_SingleHandler()
    {
        // Arrange
        const string source = """

                              using System.Threading;
                              using System.Threading.Tasks;
                              using Mediocr.Interfaces;

                              namespace TestApp;

                              public class GetUserRequest : IRequest<UserDto>
                              {
                                  public int UserId { get; set; }
                              }

                              public class UserDto
                              {
                                  public int Id { get; set; }
                                  public string Name { get; set; }
                              }

                              public class GetUserRequestHandler : IRequestHandler<GetUserRequest, UserDto>
                              {
                                  public Task<UserDto> Handle(GetUserRequest input, CancellationToken cancel)
                                  {
                                      return Task.FromResult(new UserDto { Id = input.UserId, Name = "Test" });
                                  }
                              }
                              """;

        const string expected = $$"""
                                  // <auto-generated/>
                                  // Generated by Mediocr.RequestHandlerGenerator v1.0.0
                                  // Generation time: yyyy-mm-dd HH:MM:SS UTC
                                  // Handlers discovered: 1
                                  #nullable enable
                                  
                                  using System.CodeDom.Compiler;
                                  using Microsoft.Extensions.DependencyInjection;
                                  
                                  namespace Mediocr.Interfaces
                                  {
                                      /// <summary>
                                      /// Extension methods for registering MediocR request handlers with dependency injection.
                                      /// </summary>
                                      [GeneratedCode("Mediocr.RequestHandlerGenerator", "1.0.0")]
                                      internal static class MediocRServiceCollectionExtensions
                                      {
                                          /// <summary>
                                          /// Registers all 1 discovered MediocR request handlers as scoped services.
                                          /// </summary>
                                          /// <param name="services">The service collection to add handlers to.</param>
                                          /// <returns>The service collection for chaining.</returns>
                                          internal static IServiceCollection AddMediocrHandlers(this IServiceCollection services)
                                          {
                                              services.AddScoped<global::Mediocr.Interfaces.IRequestHandler<global::TestApp.GetUserRequest, global::TestApp.UserDto>, global::TestApp.GetUserRequestHandler>();
                                  
                                              return services;
                                          }
                                      }
                                  
                                      /// <summary>
                                      /// Public extension methods for registering MediocR request handlers from TestAssembly.
                                      /// </summary>
                                      [GeneratedCode("Mediocr.RequestHandlerGenerator", "1.0.0")]
                                      public static class MediocRServiceCollectionExtensions_TestAssembly
                                      {
                                          /// <summary>
                                          /// Registers all 1 MediocR request handlers from TestAssembly as scoped services.
                                          /// </summary>
                                          /// <param name="services">The service collection to add handlers to.</param>
                                          /// <returns>The service collection for chaining.</returns>
                                          public static IServiceCollection AddMediocrHandlersFromTestAssembly(this IServiceCollection services)
                                          {
                                              return MediocRServiceCollectionExtensions.AddMediocrHandlers(services);
                                          }
                                      }
                                  }
                                  """;

        // Act
        var result = GeneratorTestHelper.RunGenerator(source, _generator);
        var generatedSource = result.GetGeneratedSource("MediocRServiceCollectionExtensions.g.cs");
        Assert.NotNull(generatedSource);
        
        generatedSource = RegexHelper.ReGenDateTime().Replace(generatedSource, "Generation time: yyyy-mm-dd HH:MM:SS UTC");
        // Assert
        NormalizeWhitespace(generatedSource).Should().Be(NormalizeWhitespace(expected));
    }
    
    [Fact]
    public void GeneratedCode_MatchesExpectedSnapshot_MultipleHandlers()
    {
        // Arrange
        const string source = """

                              using System.Threading;
                              using System.Threading.Tasks;
                              using Mediocr.Interfaces;

                              namespace TestApp.Commands;

                              public class CreateUserCommand : IRequest<int> { }
                              public class DeleteUserCommand : IRequest<bool> { }

                              public class CreateUserHandler : IRequestHandler<CreateUserCommand, int>
                              {
                                  public Task<int> Handle(CreateUserCommand input, CancellationToken cancel)
                                      => Task.FromResult(1);
                              }

                              public class DeleteUserHandler : IRequestHandler<DeleteUserCommand, bool>
                              {
                                  public Task<bool> Handle(DeleteUserCommand input, CancellationToken cancel)
                                      => Task.FromResult(true);
                              }
                              """;

        // Act
        var result = GeneratorTestHelper.RunGenerator(source, _generator);
        var generatedSource = result.GetGeneratedSource("MediocRServiceCollectionExtensions.g.cs");

        // Assert
        generatedSource.Should().NotBeNull();
        
        // Verify structure
        generatedSource.Should().Contain("namespace Mediocr.Interfaces");
        generatedSource.Should().Contain("public static class MediocRServiceCollectionExtensions");
        generatedSource.Should().Contain("public static IServiceCollection AddMediocrHandlers");
        
        // Verify both handlers are registered
        generatedSource.Should().Contain("CreateUserHandler");
        generatedSource.Should().Contain("DeleteUserHandler");
        generatedSource.Should().Contain("CreateUserCommand");
        generatedSource.Should().Contain("DeleteUserCommand");
    }
    
    [Fact]
    public void GeneratedCode_HasCorrectStructure()
    {
        // Arrange
        const string source = """

                              using System.Threading;
                              using System.Threading.Tasks;
                              using Mediocr.Interfaces;

                              namespace TestApp;

                              public class TestRequest : IRequest<string> { }

                              public class TestHandler : IRequestHandler<TestRequest, string>
                              {
                                  public Task<string> Handle(TestRequest input, CancellationToken cancel)
                                      => Task.FromResult("test");
                              }
                              """;

        // Act
        var result = GeneratorTestHelper.RunGenerator(source, _generator);
        var generatedSource = result.GetGeneratedSource("MediocRServiceCollectionExtensions.g.cs");

        // Assert - verify structure elements in order
        var lines = generatedSource!.Split('\n').Select(l => l.Trim()).ToList();
        
        var headerIndex = lines.FindIndex(l => l.Contains("// <auto-generated/>"));
        var usingIndex = lines.FindIndex(l => l.Contains("using Microsoft.Extensions.DependencyInjection;"));
        var namespaceIndex = lines.FindIndex(l => l.Contains("namespace Mediocr.Interfaces"));
        var classIndex = lines.FindIndex(l => l.Contains("public static class MediocRServiceCollectionExtensions"));
        var methodIndex = lines.FindIndex(l => l.Contains("public static IServiceCollection AddMediocrHandlers"));
        
        headerIndex.Should().BeGreaterThan(-1);
        usingIndex.Should().BeGreaterThan(headerIndex);
        namespaceIndex.Should().BeGreaterThan(usingIndex);
        classIndex.Should().BeGreaterThan(namespaceIndex);
        methodIndex.Should().BeGreaterThan(classIndex);
    }
    
    private static string NormalizeWhitespace(string text)
    {
        return string.Join("\n", 
            text.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries)
                .Select(line => line.Trim())
                .Where(line => !string.IsNullOrWhiteSpace(line)));
    }
}